service: civ6-pbc-ui
provider:
  name: aws
  stage: ${{opt:stage, self:custom.defaultStage}}
  profile: ${{self:custom.stages.${{self:provider.stage}}.profile}}
  region: us-east-1
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

plugins:
  - serverless-dotenv-plugin
  - serverless-amplify-plugin

custom:
  stages:
    dev:
      profile: civ6_dev
      branch: dev
    staging:
      profile: civ6_staging
      domainName: staging.api.civ.halfstack.software
      branch: staging
    prod:
      profile: civ6_prod
      domainName: civ.halfstack.software
      branch: master
  defaultStage: prod
  dotenv:
    path: ../../.env
  amplify:
    repository: https://github.com/brettstack/civ6-play-by-cloud-turn-notifier
    branch: ${{self:custom.stages.${{self:provider.stage}}.branch}}
    domainName: ${{self:custom.stages.${{self:provider.stage}}.domainName, ''}}
    accessToken: ${{env:GITHUB_PERSONAL_ACCESS_TOKEN}}
    defaultBuildSpecOverrides:
      baseDirectory: build