service: civ6-pbc-ui
provider:
  name: aws
  stage: ${{opt:stage, self:custom.defaultStage}}
  profile: ${{self:custom.stages.${{self:provider.stage}}.profile}}
  region: us-east-1
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

plugins:
  - serverless-dotenv-plugin
  - '@wizeline/serverless-amplify-plugin'

custom:
  defaultStage: prod
  stages:
    dev:
      profile: civ6_dev
      branch: dev
    staging:
      profile: civ6_staging
      domainName: staging.civ.halfstack.software
      branch: staging
    prod:
      profile: civ6_prod
      domainName: civ.halfstack.software
      branch: master
  dotenv:
    path: ../../.env
  amplify:
    accessTokenSecretName: AmplifyGithub3
    repository: https://github.com/brettstack/civ6-play-by-cloud-turn-notifier
    branch: ${{self:custom.stages.${{self:provider.stage}}.branch}}
    domainName: ${{self:custom.stages.${{self:provider.stage}}.domainName, ''}}
    buildSpecValues:
      artifactBaseDirectory: packages/ui/build
      preBuildWorkingDirectory: packages/ui
    # TODO: update amplify-plugin to accept custom buildSpecValues.preBuild command so we don't have to set the entire buildSpec
    buildSpec: |-
      version: 0.1
      frontend:
        phases:
          preBuild:
            commands:
              - npm ci
              - cd packages/ui
              - npm ci
          build:
            commands:
              - npm run build
        artifacts:
          baseDirectory: packages/ui/build
          files:
            - '**/*'
        cache:
          paths:
            - node_modules/**/*
resources:
  Resources:
    Civ6PbcUiAmplifyApp:
      Properties:
        # TODO: update amplify-plugin to accept CusomRules including a convenience property redirect404PagesToRoot
        CustomRules:
          - Source: </^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$)([^.]+$)/>
            Target: /
            Status: 200