service: civ6-pbc-ui
provider:
  name: aws
  stage: ${{opt:stage, self:custom.defaultStage}}
  profile: ${{self:custom.stages.${{self:provider.stage}}.profile}}
  region: us-east-1
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

plugins:
  - serverless-dotenv-plugin
  - ../../../serverless-amplify-plugin

custom:
  defaultStage: prod
  stages:
    dev:
      profile: civ6_dev
      branch: dev
    staging:
      profile: civ6_staging
      domainName: staging.civ.halfstack.software
      branch: staging
    prod:
      profile: civ6_prod
      domainName: civ.halfstack.software
      branch: master
  dotenv:
    path: ../../.env
  amplify:
    accessTokenSecretName: AmplifyGithub3
    repository: https://github.com/brettstack/civ6-play-by-cloud-turn-notifier
    branch: ${{self:custom.stages.${{self:provider.stage}}.branch}}
    domainName: ${{self:custom.stages.${{self:provider.stage}}.domainName, ''}}
    buildSpec: |-
      version: 0.1
      frontend:
        phases:
          preBuild:
            commands:
              - cd packages/ui
              - npm ci
          build:
            commands:
              - npm run build
        artifacts:
          baseDirectory: packages/ui/build
          files:
            - '**/*'
        cache:
          paths:
            - node_modules/**/*