service: chaos-arena-db
provider:
  name: aws
  stage: ${{opt:stage, self:custom.defaultStage}}
  profile: ${{self:custom.stages.${{self:provider.stage}}.profile}}
  runtime: nodejs8.10
  profile: ${{self:custom.profiles.${{self:provider.stage}}}}
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

plugins:
  - serverless-dynamodb-local

custom:
  defaultStage: prod
  stages:
    dev:
      profile: civ6_dev
      branch: dev
    staging:
      profile: civ6_staging
      subdomain: staging.civ
      domainName: halfstack.software
      branch: staging
    prod:
      profile: civ6_prod
      subdomain: civ
      domainName: halfstack.software
      branch: master
  dynamodb:
    stages:
        - dev # ?
    start:
      port: 889
      migrate: true
      seed: true
    seed:
      CivPbc:
        sources:
          - table: CivPbc
            sources: [./db-seed/CivPbc.json]

resources:
  Resources:
    AbilityTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: CivPbc
          BillingMode: PAY_PER_REQUEST
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: false
          KeySchema:
            - KeyType: HASH
              AttributeName: pk
            - KeyType: RANGE
              AttributeName: sk
          AttributeDefinitions:
            - AttributeName: pk
              AttributeType: S
            - AttributeName: sk
              AttributeType: S

  Outputs:
    DynamoDbGameTableConsoleUrl:
      Description: Console URL for the DynamoDB Table.
      Value: !Sub 'https://console.aws.amazon.com/dynamodb/home?region=${AWS::Region}#tables:selected=${HeroTable}'
