name: 'Delete old artifacts'
on:
  workflow_dispatch:
  # schedule:
  #   # Run weekly
  #   - cron: "0 0 * * 0"

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 10 minutes
