name: Deploy on release published

on:
  release:
    types:
    - published

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [db, api, ui]
    steps:
    - name: Download release
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        tag: latest
        file: civ6-pbc-${{ matrix.package }}.zip

    - name: Unzip release package
      run: unzip civ6-pbc-${{ matrix.package }}.zip

    - name: Setup AWS Credentials
      run: |
        mkdir ~/.aws
        echo "[civ6_prod]
        aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
    
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install package
      run: npm i
    
    - name: Deploy package
      run: npm run deploy-package