name: Test and release

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [db, api, ui]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install root
      run: npm ci

    - name: Install package
      working-directory: "./packages/${{ matrix.package }}"
      run: npm ci

    - name: Test
      working-directory: "./packages/${{ matrix.package }}"
      run: npm test

    # - name: Deploy staging
    #   working-directory: "./packages/${{ matrix.package }}"
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.package === 'api'
    #   run: npm run deploy-staging -- --runId=${{ github.run_id }}
    
    - name: Package
      working-directory: "./packages/${{ matrix.package }}"
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: npm run package
    
    - name: Upload package artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: "./packages/${{ matrix.package }}/civ6-pbc-${{ matrix.package }}.zip"

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install root dependencies
      run: npm ci
      
    - name: Download package artifact
      uses: actions/download-artifact@v1
      with:
        name: release
        path: release
      
    - name: Release
      run: npx semantic-release
      env:
        # NOTE: GitHub Actions won't trigger on release when using the default GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
